### ISSUE TITLE
Something fishy is going on with indexer

### ISSUE THREAD

**Issue by trokas** [log0ymxm/spark-mapper#1]
Let's suppose that I have following inputs:

```scala
dist.entries.toDF().show()
+---+---+------------------+
|  i|  j|             value|
+---+---+------------------+
|  0|  1|1.8608118357527468|
|  1|  2|1.6111741451351849|
|  0|  2|0.8767049428178864|
+---+---+------------------+

filtered.rows.toDF().show()
+-----+--------------------+
|index|              vector|
+-----+--------------------+
|    0|[2.7146152801920156]|
|    1| [3.403557805961366]|
|    2|[1.7454678862779096]|
+-----+--------------------+
```

Then

```
Mapper.mapper(
  sc,
  dist,
  filtered
)
```

Throws exception:

```
 java.lang.IndexOutOfBoundsException: 0
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
        at scala.collection.immutable.List.apply(List.scala:84)
        at com.github.log0ymxm.mapper.Mapper$$anonfun$7.apply(Mapper.scala:70)
        at com.github.log0ymxm.mapper.Mapper$$anonfun$7.apply(Mapper.scala:67)
        ...
```

Any ideas why?

**Comment by trokas** [comment]
Ah, this is not an issue, I had to fiddle around with coverIntervals to make it work... Logical ;)
